# Generated by Django 5.0.6 on 2024-06-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('description', models.TextField(default='Description par défaut')),
                ('type_pro', models.CharField(default='Type par défaut', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('description', models.TextField(default='Description par défaut')),
                ('color', models.CharField(default='Couleur par défaut', max_length=50)),
                ('size', models.CharField(default='Taille par défaut', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('description', models.TextField(default='Description par défaut')),
                ('color', models.CharField(default='Couleur par défaut', max_length=100)),
                ('type_pro', models.CharField(default='Type par défaut', max_length=255)),
                ('size_M_quantity', models.IntegerField(default=0)),
                ('size_L_quantity', models.IntegerField(default=0)),
                ('size_XL_quantity', models.IntegerField(default=0)),
                ('size_2XL_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Racket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('description', models.TextField(default='Description par défaut')),
                ('type_pro', models.CharField(default='Type par défaut', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('description', models.TextField(default='Description par défaut')),
                ('color', models.CharField(default='Couleur par défaut', max_length=100)),
                ('size_39_quantity', models.IntegerField(default=0)),
                ('size_40_quantity', models.IntegerField(default=0)),
                ('size_41_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shuttle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('description', models.TextField(default='Description par défaut')),
                ('type_pro', models.CharField(default='Type par défaut', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('description', models.TextField(default='Description par défaut')),
                ('type_pro', models.CharField(default='Type par défaut', max_length=255)),
            ],
        ),
    ]
