# Generated by Django 5.0.6 on 2024-06-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='color',
            field=models.CharField(default='Couleur par défaut', max_length=100),
        ),
        migrations.AddField(
            model_name='accessory',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bag',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='clothe',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='racket',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shoe',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='string',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
