# Generated by Django 5.0.6 on 2024-06-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessory_images/'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bag_images/'),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clothe_images/'),
        ),
        migrations.AlterField(
            model_name='racket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='racket_images/'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shoe_images/'),
        ),
        migrations.AlterField(
            model_name='shuttle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shuttle_images/'),
        ),
        migrations.AlterField(
            model_name='string',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='string_images/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
